name: Update check status
description: ""

runs:
  using: "composite"
  steps:
    - name: Create status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "${{ job.status }}",
          "context": "build-and-deploy-web",
          "target_url": "${{ github.event.workflow_run.html_url }}"
          }' \
        --fail