name: Update check status
description: ""

inputs:
  token:
    description: 'secrets.GITHUB_TOKEN'
    required: true

  status_name:
    description: 'build-and-deploy-web'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Update check status
      shell: pwsh
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
        --header 'authorization: Bearer ${{ inputs.token }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "${{ job.status }}",
          "context": "${{ inputs.status_name }}",
          "target_url": "${{ github.event.workflow_run.html_url }}"
          }' \
        --fail