workspace {

    model {
        user = person "User"
        admin = person "Admin"
        softwareSystem = softwareSystem "Siren" "All your musical sources in one place" {
            musicPlayer = container "Music Player" "Cross platform audio player" {
                user -> this "Uses to listen the music"
            }
            
            sirenAI = container "Siren AI" {
                // musicPlayer -> this "Reads the tacks to play"
                smartTrack = component "Smart Track" "Generated by AI to match player request expectations" {
                    musicPlayer -> this "Reads the tack to play (passing audio profile)"
                }
                
                beatMatchbox = component "Beat-Matchbox" "“pitch shifting” an upcoming track to match its tempo" {
                    smartTrack -> this "Uses to beat match the next track with the current"
                }
                harmonicMixer = component "Harmonic Mixer" "Creates more harmonic and melodic mix between songs" {
                    smartTrack -> this "Uses to mix the next with the current track"
                }
            }
            smartShufflingTracks = container "Smart shuffling tracks" "Remembers what songs been played and learn to shuffle not on hours but on days, weeks, months" {
                smartShufflingTracksComponent = component "Smart shuffling tracks" {
                    smartTrack -> this "Gets next track to play"
                }
                alreadyPlayedTracks = component "AlreadyPlayedTracks" "Tracks that been recenlty played for this client" {
                    smartShufflingTracksComponent -> this "Reads tracks metadata that been played"
                }
                timeOfTheDayTracks = component "Time of the day tracks" "Filters the tracks which appropriate for requested time of the day" {
                    smartShufflingTracksComponent -> this "Chooses one of the tracks""
                }
                tempoTracks = component "Tempo tracks" "Tracks that fit specific tempo" {
                    smartShufflingTracksComponent -> this "Reads tracks for specific tempo"
                    timeOfTheDayTracks -> this "Reads tracks for specific genre"
                }
                genreTracks = component "Genre tracks" "Tracks that fit specific genre" {
                    tempoTracks -> this "Reads tracks for specific genre"
                    smartShufflingTracksComponent -> this "Reads tracks for specific genre"
                    timeOfTheDayTracks -> this "Reads tracks for specific genre"
                }
            }
            profileManager = container "Audio Profiles" {
                musicPlayer -> this "Reads user's audio profile"
                admin -> this "Manages users' profiles to meet audio expectations"
            }
            musicStore = container "Music Store" {
                sirenAI -> this "Reads tracks and metadata"
                smartTrack -> this "Reads current track audio stream"
                genreTracks -> this "Reads tracks metadata for specific genre"
                tempoTracks -> this "Reads tracks metadata for specifi tempo"
            }
            container "Track Metadata Database" {
                musicStore -> this "Reads from and writes to"
            }
        }
        appleMusic = softwareSystem "Apple Music" {
           profileManager -> this "Uses for tracklist generation"
        }
        spotify = softwareSystem "Spotify" {
           profileManager -> this "Uses for tracklist generation"
        }
        soundtrackYourBrand = softwareSystem "Soundtrack Your Brand" "Background music for businesses that want it all (https://www.soundtrackyourbrand.com)" {
           musicStore -> this "Reads metadata and audio blobs"
        }
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout lr
        }

        container softwareSystem {
            include *
            autolayout lr
        }
        
        component sirenAI {
            include *
            autolayout lr
        }
        
        component smartShufflingTracks {
            include *
            autolayout lr
        }

        theme default
    }
}