workspace {

    model {
        user = person "User"
        admin = person "Admin"
        dj = person "DJ"
        softwareSystem = softwareSystem "Pagina Blanca" "All your musical sources in one place" {
            musicPlayer = container "Music Player" {
                user -> this "Uses to listen the music"
            }
            
            smartDJ = container "Smart DJ (AI) " {
                dj -> this "Manges the tracks generation"
                musicPlayer -> this "Reads the tacks to play"
                smartTrack = component "Smart Track" "Generated by AI to match player request expectations" {
                    musicPlayer -> this "Reads the tack to play"
                }
                
                beatMatchbox = component "Beat-Matchbox" "“pitch shifting” an upcoming track to match its tempo" {
                    smartTrack -> this "Uses to beat match the next track with the current"
                }
                harmonicMixer = component "Harmonic Mixer" "Creates more harmonic and melodic mix between songs" {
                    smartTrack -> this "Uses to mix the next with the current track"
                }
            }
            smartShufflingTracks = container "Smart shuffling tracks" "Remembers what songs been played and learn to shuffle not on hours but on days, weeks, months" {
                smartShufflingTracksComponent = component "Smart shuffling tracks" {
                    smartTrack -> this "Chooses one of the next tracks"
                }
                alreadyPlayedTracks = component "AlreadyPlayedTracks" "Tracks that been recenlty played for this client" {
                    smartShufflingTracksComponent -> this "Reads tracks metadata that been played"
                }
                timeOfTheDayTracks = component "Time of the day tracks" "Filters the tracks which appropriate for requested time of the day" {
                    smartShufflingTracksComponent -> this "Chooses one of the tracks""
                }
                tempoTracks = component "Tempo tracks" "Tracks that fit specific tempo" {
                    smartShufflingTracksComponent -> this "Reads tracks for specific tempo"
                    timeOfTheDayTracks -> this "Reads tracks for specific genre"
                }
                genreTracks = component "Genre tracks" "Tracks that fit specific genre" {
                    tempoTracks -> this "Reads tracks for specific genre"
                    smartShufflingTracksComponent -> this "Reads tracks for specific genre"
                    timeOfTheDayTracks -> this "Reads tracks for specific genre"
                }
            }
            musicManager = container "Music Manager" {
                admin -> this "Manges music collections"
            }
            musicStore = container "Music Store" {
                smartDJ -> this "Reads tracks and metadata"
                musicManager -> this "Updates music collection"
                genreTracks -> this "Reads tracks and metadata"
                tempoTracks -> this "Reads tracks and metadata"
            }
            container "Track Meta Database" {
                musicStore -> this "Reads from and writes to"
            }
            container "Track Blob Database" {
                musicStore -> this "Reads from and writes to"
            }
        }
        appleMusic = softwareSystem "Apple Music" {
           musicManager -> this "Uses as a music source"
        }
        spotify = softwareSystem "Spotify" {
           musicManager -> this "Uses as a music source"
        }
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout lr
        }

        container softwareSystem {
            include *
            autolayout lr
        }
        
        component smartDJ {
            include *
            autolayout lr
        }
        
        component smartShufflingTracks {
            include *
            autolayout lr
        }

        theme default
    }
}