name: Build and test

on:
  push:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - '**.cs'
      - '**.csproj'
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        
      - name: Restore dependencies
        run: dotnet restore src/SirenApp/SirenApp.csproj --ignore-failed-sources

      - name: Build 
        run: dotnet build src/SirenApp/SirenApp.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/Siren.UnitTests/Siren.UnitTests.csproj --no-restore --logger "trx;LogFileName=test-results.trx" || true
  
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
