name: Build and test

on:
  push:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - '**.cs'
      - '**.csproj'
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set test variable
        id: set-variable
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            echo "targetFramework=net8.0-android" >> $GITHUB_ENV
            echo "::set-output name=targetFramework=net8.0-android"
          else if [ ${{ matrix.os }} == 'windows-latest' ]; then
            echo "tatargetFrameworkrget=net8.0-windows" >> $GITHUB_ENV
            echo "::set-output name=targetFramework=net8.0-windows"
          else
            echo "targetFramework=net8.0-ios" >> $GITHUB_ENV
            echo "::set-output name=targetFramework=net8.0-ios"
          fi
        shell: bash

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
     
      - name: Restore dependencies
        run: dotnet restore -p:TargetFramework=${{ env.targetFramework }}

      - name: Build 
        run: dotnet build -p:TargetFramework=${{ env.targetFramework }} --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
