name: Build and test

on:
  push:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - '**.cs'
      - '**.csproj'
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
     
      - name: Restore dependencies
        run: dotnet restore -p:TargetFramework=net8.0

      - name: Build 
        run: dotnet build -p:TargetFramework=net8.0 --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
