name: Publish to azure static web apps

on:
  workflow_run:
    workflows: ["build-and-test"]
    types: 
      - completed
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build_and_deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: build-and-deploy-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: linux
          installJDK: false

      - run: |
          dotnet build src/Siren.Wasm/Siren.Wasm.csproj -c Release

      - name: Determine Status
        id: determine_status
        run: echo "::set-output name=status::$(if [ $? -eq 0 ]; then echo 'success'; else echo 'failure'; fi)"
    
      - name: Set Status Check
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const status = process.env.STATUS;
            github.repos.createStatus({
              ...context.repo,
              sha: context.sha,
              state: status,
              target_url: 'https://example.com',
              description: 'Web build succeeded',
              context: 'build-and-deploy-web '
            });

      - name: Build And Deploy
        if: github.event_name == 'push'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_003F4A803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/Siren.Wasm/bin/Release/net8.0/dist"
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      