name: build-and-deploy-web

on:
  workflow_run:
    workflows: ["build-and-test"]
    types: 
      - completed
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build_and_deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: build-and-deploy-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: wasm

      - run: |
          dotnet build src/Siren.Wasm/Siren.Wasm.csproj -c Release

      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "build-and-deploy-web",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail

      - name: Build And Deploy
        if: github.event_name == 'push'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_003F4A803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/Siren.Wasm/bin/Release/net8.0/dist"
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      