name: build-and-deploy-android

on:
  workflow_run:
    workflows: ["build-and-test"]
    types: 
      - completed
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  build_and_deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: build-and-deploy-android
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: android
      - name: Setup Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" > siren.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch siren.keystore.asc > siren.keystore
          echo "Keystore path: $(pwd)/siren.keystore"

      - name: Build and Archive
        run: |
          echo "$(ls)"
          dotnet publish src/Siren.Mobile/Siren.Mobile.csproj -f net8.0-android -c Release /p:AndroidSigningKeyStore=siren.keystore /p:AndroidSigningKeyAlias=githubactionskey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}"
      - name: Upload a Build Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3.1.0
        with:
          path: |
            ./**/*.aab
            ./**/*.apk
      - name: GitHub Action for AppCenter Distribute Mobile
        if: github.event_name != 'pull_request'
        uses: familiohq/appcenter-distribute-action@0.2
        with:
          app_secret: ${{ secrets.APP_CENTER_API_TOKEN }}
          file_path: |
            ./**/*.aab
            ./**/*.apk
          group: "Siren"
      - name: Update Check Status
        if: always()
        uses: "./.github/steps/update_check_status"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status_name: "build-and-deploy-android"